<a href="https://colab.research.google.com/github/Jacqueline-dev/projetoETL/blob/main/limpeza.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("/content/ocorrencia.csv", encoding='cp1252', sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
df.tail(5)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
6764,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6765,39527,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,0,1,NÃO
6766,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6767,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6768,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [4]:
df.loc[1:3]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
3,81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [5]:
df.loc[1, 'ocorrencia_cidade']

'VITÓRIA'

In [6]:
df.loc[[10,40]]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,81017,81017,81017,81017,81017,INCIDENTE GRAVE,NaN,NaN,GOIÂNIA,GO,...,2022-09-30,13:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
40,80978,80978,80978,80978,80978,ACIDENTE,NaN,NaN,SANTA HELENA DE GOIÁS,GO,...,2022-09-09,15:40:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO

In [7]:
df.loc[:,'ocorrencia_cidade']

0                SÃO PAULO
1                  VITÓRIA
2                AMERICANA
3           BELO HORIZONTE
4                   MANAUS
               ...
6764               PELOTAS
6765    LUCAS DO RIO VERDE
6766        RIO DE JANEIRO
6767                 BELÉM
6768        RIO DE JANEIRO
Name: ocorrencia_cidade, Length: 6769, dtype: object

In [8]:
df.codigo_ocorrencia.is_unique

True

In [9]:
df.set_index('codigo_ocorrencia', inplace=True)

In [10]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,BRASIL,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [11]:
df.loc[81025]

codigo_ocorrencia1                              81025
codigo_ocorrencia2                              81025
codigo_ocorrencia3                              81025
codigo_ocorrencia4                              81025
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                              MANAUS
ocorrencia_uf                                      AM
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBEG
ocorrencia_dia                    2022-10-05 00:00:00
ocorrencia_hora                              20:56:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       ***
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 81025, dtype: object

In [12]:
df.reset_index(drop=True, inplace=True)

In [13]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
1,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,BRASIL,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [14]:
# alterando dados
df.loc[0, 'ocorrencia_aerodromo'] = ''

In [15]:
df.head(1)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM

In [16]:
df.loc[1] = 20

In [17]:
df.head(2)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,2022-10-09 00:00:00,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20

In [18]:
df.loc[: , 'total_recomendacoes'] = 10

In [19]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,2022-10-09 00:00:00,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,10,20,20
2,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,2022-10-06 00:00:00,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,2022-10-06 00:00:00,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,2022-10-05 00:00:00,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,2010-01-05 00:00:00,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,2010-01-04 00:00:00,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO
6766,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO
6767,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2010-01-03 00:00:00,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO
6768,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,2010-01-03 00:00:00,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO

In [20]:
df['ocorrencia_uf_bkp'] = df.ocorrencia_uf

In [21]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ

In [22]:
df.loc[df.ocorrencia_uf == 'SP', ['ocorrencia_classificacao']] = 'GRAVE'

In [23]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ

In [24]:
df.loc[df.ocorrencia_uf == 'SP']

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
2,81023,81023,81023,81023,GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
13,81003,81003,81003,81003,GRAVE,NaN,NaN,ARAÇATUBA,SP,BRASIL,...,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
14,81001,81001,81001,81001,GRAVE,NaN,NaN,BRAGANÇA PAULISTA,SP,BRASIL,...,20:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
18,80997,80997,80997,80997,GRAVE,NaN,NaN,GUARULHOS,SP,BRASIL,...,11:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6741,39768,39768,39768,39768,GRAVE,NaN,NaN,CAMPINAS,SP,BRASIL,...,20:45:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
6743,39847,39847,39847,39847,GRAVE,NaN,NaN,SOROCABA,SP,BRASIL,...,13:10:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
6751,39809,39809,39809,39809,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,15:00:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
6753,39828,39828,39828,39828,GRAVE,***,***,SANTOS,SP,BRASIL,...,17:45:00,***,NaN,NaN,NÃO,NaN,10,1,NÃO,SP
6759,40069,40069,40069,40069,GRAVE,-235.069.444.444,-466.341.666.667,SÃO PAULO,SP,BRASIL,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,19/11/2012,10,1,NÃO,SP

In [25]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ

In [ ]:
"""
DADOS PARA LIMPAR

ocorrencia_uf
**
ocorrencia_aerodromo
###!
####
****
*****

ocorrencia_hora
NULL

"""

In [26]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,AM

In [27]:
df.loc[df.ocorrencia_aerodromo == '****', ['ocorrencia_aerodromo']] = pd.NA

In [28]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,NaN,NaN,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,NaN,NaN,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,10,1,NÃO,AM

In [29]:
df.replace(['**', '***', '###!', '####', '****', '*****', 'NULL'], pd.NA, inplace=True)

In [30]:
df.tail()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
6764,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,<NA>,<NA>,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,<NA>,NÃO,NaN,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,10,1,NÃO,RJ

In [31]:
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2364
ocorrencia_longitude              2366
ocorrencia_cidade                    0
ocorrencia_uf                        4
ocorrencia_pais                      0
ocorrencia_aerodromo              2417
ocorrencia_dia                       0
ocorrencia_hora                      2
investigacao_aeronave_liberada    2307
investigacao_status                341
divulgacao_relatorio_numero       4371
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4987
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    4
dtype: int64

In [32]:
df.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               2364
ocorrencia_longitude              2366
ocorrencia_cidade                    0
ocorrencia_uf                        4
ocorrencia_pais                      0
ocorrencia_aerodromo              2417
ocorrencia_dia                       0
ocorrencia_hora                      2
investigacao_aeronave_liberada    2307
investigacao_status                341
divulgacao_relatorio_numero       4371
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4987
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
ocorrencia_uf_bkp                    4
dtype: int64

In [33]:
df.fillna(10, inplace=True)

In [34]:
df.isnull().sum()

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
ocorrencia_uf_bkp                 0
dtype: int64

In [35]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM

In [36]:
df.replace([0], pd.NA, inplace=True)

In [37]:
df.isnull().sum()

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
ocorrencia_uf_bkp                 0
dtype: int64

In [38]:
df.fillna(value={'total_recomendacoes':10}, inplace=True)

In [39]:
df.isnull().sum()

codigo_ocorrencia1                0
codigo_ocorrencia2                0
codigo_ocorrencia3                0
codigo_ocorrencia4                0
ocorrencia_classificacao          0
ocorrencia_latitude               0
ocorrencia_longitude              0
ocorrencia_cidade                 0
ocorrencia_uf                     0
ocorrencia_pais                   0
ocorrencia_aerodromo              0
ocorrencia_dia                    0
ocorrencia_hora                   0
investigacao_aeronave_liberada    0
investigacao_status               0
divulgacao_relatorio_numero       0
divulgacao_relatorio_publicado    0
divulgacao_dia_publicacao         0
total_recomendacoes               0
total_aeronaves_envolvidas        0
ocorrencia_saida_pista            0
ocorrencia_uf_bkp                 0
dtype: int64

In [40]:
df['total_recomendacoes_bkp'] = df.total_recomendacoes

In [41]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp,total_recomendacoes_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP,10
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,10,20,20,20,10
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP,10
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG,10
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM,10

In [42]:
df.drop(['total_recomendacoes_bkp'], axis=1, inplace=True)

In [43]:
df.head()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM

In [44]:
df.dropna()

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ

In [45]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ

In [47]:
df.dropna(subset=['ocorrencia_uf'])

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ

In [48]:
df.drop_duplicates(inplace=True)

In [49]:
df

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_uf_bkp
0,81027,81027,81027,81027,GRAVE,10,10,SÃO PAULO,SP,BRASIL,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,10,10,1,SIM,SP
1,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,10,20,20,20
2,81023,81023,81023,81023,GRAVE,10,10,AMERICANA,SP,BRASIL,...,15:30:00,SIM,FINALIZADA,10,NÃO,10,10,1,SIM,SP
3,81029,81029,81029,81029,INCIDENTE,10,10,BELO HORIZONTE,MG,BRASIL,...,00:44:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,MG
4,81025,81025,81025,81025,INCIDENTE,10,10,MANAUS,AM,BRASIL,...,20:56:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,INCIDENTE,10,10,PELOTAS,RS,BRASIL,...,19:25:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RS
6765,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,BRASIL,...,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,10,1,NÃO,MT
6766,40211,40211,40211,40211,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,12:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ
6767,40349,40349,40349,40349,INCIDENTE,10,10,BELÉM,PA,BRASIL,...,11:05:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,PA
6768,40351,40351,40351,40351,INCIDENTE,10,10,RIO DE JANEIRO,RJ,BRASIL,...,03:00:00,SIM,FINALIZADA,10,NÃO,10,10,1,NÃO,RJ