<a href="https://colab.research.google.com/github/Jacqueline-dev/projetoETL/blob/main/transformacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandera

In [4]:
import pandas as pd

In [5]:
import pandera as pa

In [6]:
valores_ausentes = ['**','###!','####','****','*****','NULL']
df = pd.read_csv("/content/ocorrencia.csv", encoding='cp1252', sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True, na_values=valores_ausentes)
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
3,81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5,81019,81019,81019,81019,81019,ACIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2022-10-03,20:50:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
6,81022,81022,81022,81022,81022,INCIDENTE,NaN,NaN,LOBATO,PR,...,2022-10-03,15:38:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
7,81021,81021,81021,81021,81021,ACIDENTE,NaN,NaN,NOVA BANDEIRANTES,MT,...,2022-10-02,19:00:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
8,81009,81009,81009,81009,81009,INCIDENTE GRAVE,NaN,NaN,NAVIRAÍ,MS,...,2022-10-01,10:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
9,81012,81012,81012,81012,81012,INCIDENTE,NaN,NaN,LINHARES,ES,...,2022-09-30,12:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [7]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,3), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes": pa.Column(pa.Int)   
    }
)

In [8]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
3,81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,2022-10-06,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4,81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6764,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6765,39527,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,0,1,NÃO
6766,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6767,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6768,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [9]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

In [10]:
df.loc[1]

codigo_ocorrencia                               81030
codigo_ocorrencia1                              81030
codigo_ocorrencia2                              81030
codigo_ocorrencia3                              81030
codigo_ocorrencia4                              81030
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                             VITÓRIA
ocorrencia_uf                                      ES
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBVT
ocorrencia_dia                    2022-10-09 00:00:00
ocorrencia_hora                              16:20:00
investigacao_aeronave_liberada                    SIM
investigacao_status                             ATIVA
divulgacao_relatorio_numero                 A DEFINIR
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 1, dtype: object

In [11]:
df.iloc[1]

codigo_ocorrencia                               81030
codigo_ocorrencia1                              81030
codigo_ocorrencia2                              81030
codigo_ocorrencia3                              81030
codigo_ocorrencia4                              81030
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                             VITÓRIA
ocorrencia_uf                                      ES
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBVT
ocorrencia_dia                    2022-10-09 00:00:00
ocorrencia_hora                              16:20:00
investigacao_aeronave_liberada                    SIM
investigacao_status                             ATIVA
divulgacao_relatorio_numero                 A DEFINIR
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 1, dtype: object

In [12]:
df.iloc[-1]

codigo_ocorrencia                               40351
codigo_ocorrencia1                              40351
codigo_ocorrencia2                              40351
codigo_ocorrencia3                              40351
codigo_ocorrencia4                              40351
ocorrencia_classificacao                    INCIDENTE
ocorrencia_latitude                               NaN
ocorrencia_longitude                              NaN
ocorrencia_cidade                      RIO DE JANEIRO
ocorrencia_uf                                      RJ
ocorrencia_pais                                BRASIL
ocorrencia_aerodromo                             SBRJ
ocorrencia_dia                    2010-01-03 00:00:00
ocorrencia_hora                              03:00:00
investigacao_aeronave_liberada                    SIM
investigacao_status                        FINALIZADA
divulgacao_relatorio_numero                       NaN
divulgacao_relatorio_publicado                    NÃO
divulgacao_dia_publicacao                         NaN
total_recomendacoes                                 0
total_aeronaves_envolvidas                          1
ocorrencia_saida_pista                            NÃO
Name: 6768, dtype: object

In [13]:
df.tail()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
6764,40324,40324,40324,40324,40324,INCIDENTE,NaN,NaN,PELOTAS,RS,...,2010-01-05,19:25:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6765,39527,39527,39527,39527,39527,ACIDENTE,-131.066.666.667,-559.930.555.556,LUCAS DO RIO VERDE,MT,...,2010-01-04,17:30:00,SIM,FINALIZADA,A-539/CENIPA/2018,SIM,28/10/2019,0,1,NÃO
6766,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,2010-01-03,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6767,40349,40349,40349,40349,40349,INCIDENTE,NaN,NaN,BELÉM,PA,...,2010-01-03,11:05:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6768,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,2010-01-03,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO

In [14]:
df.iloc[10:15]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,81017,81017,81017,81017,81017,INCIDENTE GRAVE,NaN,NaN,GOIÂNIA,GO,...,2022-09-30,13:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
11,81006,81006,81006,81006,81006,INCIDENTE,NaN,NaN,UBERLÂNDIA,MG,...,2022-09-28,12:55:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
12,81014,81014,81014,81014,81014,ACIDENTE,NaN,NaN,BOA VISTA,RR,...,2022-09-27,00:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
13,81003,81003,81003,81003,81003,INCIDENTE GRAVE,NaN,NaN,ARAÇATUBA,SP,...,2022-09-26,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
14,81001,81001,81001,81001,81001,INCIDENTE,NaN,NaN,BRAGANÇA PAULISTA,SP,...,2022-09-25,20:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [15]:
df.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
10,81017,81017,81017,81017,81017,INCIDENTE GRAVE,NaN,NaN,GOIÂNIA,GO,...,2022-09-30,13:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
11,81006,81006,81006,81006,81006,INCIDENTE,NaN,NaN,UBERLÂNDIA,MG,...,2022-09-28,12:55:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
12,81014,81014,81014,81014,81014,ACIDENTE,NaN,NaN,BOA VISTA,RR,...,2022-09-27,00:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
13,81003,81003,81003,81003,81003,INCIDENTE GRAVE,NaN,NaN,ARAÇATUBA,SP,...,2022-09-26,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
14,81001,81001,81001,81001,81001,INCIDENTE,NaN,NaN,BRAGANÇA PAULISTA,SP,...,2022-09-25,20:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
15,81018,81018,81018,81018,81018,ACIDENTE,NaN,NaN,LONTRAS,SC,...,2022-09-24,20:05:00,NÃO,ATIVA,A-108/CENIPA/2022,NÃO,NaN,0,1,NÃO

In [16]:
df.loc[:,'ocorrencia_uf']

0       SP
1       ES
2       SP
3       MG
4       AM
        ..
6764    RS
6765    MT
6766    RJ
6767    PA
6768    RJ
Name: ocorrencia_uf, Length: 6769, dtype: object

In [17]:
df['ocorrencia_uf']

0       SP
1       ES
2       SP
3       MG
4       AM
        ..
6764    RS
6765    MT
6766    RJ
6767    PA
6768    RJ
Name: ocorrencia_uf, Length: 6769, dtype: object

In [18]:
df.isna().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1638
ocorrencia_longitude              1639
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo                 0
ocorrencia_dia                       0
ocorrencia_hora                      2
investigacao_aeronave_liberada     238
investigacao_status                341
divulgacao_relatorio_numero        789
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4988
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [19]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1638
ocorrencia_longitude              1639
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo                 0
ocorrencia_dia                       0
ocorrencia_hora                      2
investigacao_aeronave_liberada     238
investigacao_status                341
divulgacao_relatorio_numero        789
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         4988
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [20]:
filtro = df.ocorrencia_uf.isnull()
df.loc[filtro]

Empty DataFrame
Columns: [codigo_ocorrencia, codigo_ocorrencia1, codigo_ocorrencia2, codigo_ocorrencia3, codigo_ocorrencia4, ocorrencia_classificacao, ocorrencia_latitude, ocorrencia_longitude, ocorrencia_cidade, ocorrencia_uf, ocorrencia_pais, ocorrencia_aerodromo, ocorrencia_dia, ocorrencia_hora, investigacao_aeronave_liberada, investigacao_status, divulgacao_relatorio_numero, divulgacao_relatorio_publicado, divulgacao_dia_publicacao, total_recomendacoes, total_aeronaves_envolvidas, ocorrencia_saida_pista]
Index: []

[0 rows x 22 columns]

In [21]:
filtro = df.ocorrencia_aerodromo.isnull()
df.loc[filtro]

Empty DataFrame
Columns: [codigo_ocorrencia, codigo_ocorrencia1, codigo_ocorrencia2, codigo_ocorrencia3, codigo_ocorrencia4, ocorrencia_classificacao, ocorrencia_latitude, ocorrencia_longitude, ocorrencia_cidade, ocorrencia_uf, ocorrencia_pais, ocorrencia_aerodromo, ocorrencia_dia, ocorrencia_hora, investigacao_aeronave_liberada, investigacao_status, divulgacao_relatorio_numero, divulgacao_relatorio_publicado, divulgacao_dia_publicacao, total_recomendacoes, total_aeronaves_envolvidas, ocorrencia_saida_pista]
Index: []

[0 rows x 22 columns]

In [22]:
filtro = df.ocorrencia_hora.isnull()
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
56,80938,80938,80938,80938,80938,INCIDENTE,-5.368.055.555.555,-4.913.805.555.555,MARABÁ,PA,...,2022-08-29,NaN,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2671,78823,78823,78823,78823,78823,INCIDENTE,***,***,CORUMBÁ,MS,...,2017-07-09,NaN,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [23]:
df.count()

codigo_ocorrencia                 6769
codigo_ocorrencia1                6769
codigo_ocorrencia2                6769
codigo_ocorrencia3                6769
codigo_ocorrencia4                6769
ocorrencia_classificacao          6769
ocorrencia_latitude               5131
ocorrencia_longitude              5130
ocorrencia_cidade                 6769
ocorrencia_uf                     6769
ocorrencia_pais                   6769
ocorrencia_aerodromo              6769
ocorrencia_dia                    6769
ocorrencia_hora                   6767
investigacao_aeronave_liberada    6531
investigacao_status               6428
divulgacao_relatorio_numero       5980
divulgacao_relatorio_publicado    6769
divulgacao_dia_publicacao         1781
total_recomendacoes               6769
total_aeronaves_envolvidas        6769
ocorrencia_saida_pista            6769
dtype: int64

In [24]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
2836,66432,66432,66432,66432,66432,INCIDENTE GRAVE,-203.861.111.111,-404.888.888.889,VITÓRIA,ES,...,2017-02-21,11:47:00,NaN,FINALIZADA,IG-031/CENIPA/2017,SIM,02/10/2020,12,1,NÃO
3970,52265,52265,52265,52265,52265,ACIDENTE,-239.597.222.222,-463.269.444.444,SANTOS,SP,...,2014-08-13,13:03:00,NaN,FINALIZADA,A-134/CENIPA/2014,SIM,11/01/2016,13,1,NÃO
4796,47938,47938,47938,47938,47938,INCIDENTE,-158.691.666.667,-479.208.333.333,BRASÍLIA,DF,...,2013-04-13,18:00:00,***,FINALIZADA,I-067/CENIPA/2013,SIM,10/07/2013,11,1,NÃO
5705,45554,45554,45554,45554,45554,INCIDENTE GRAVE,-189.669.444.444,-482.252.777.778,UBERLÂNDIA,MG,...,2011-11-15,02:15:00,NaN,FINALIZADA,IG-018/CENIPA/2013,SIM,16/07/2013,20,1,SIM
5885,44888,44888,44888,44888,44888,INCIDENTE GRAVE,\t-25.53111111\t,\t-49.17555556\t,SÃO JOSÉ DOS PINHAIS,PR,...,2011-07-15,17:05:00,SIM,FINALIZADA,IG-532/CENIPA/2015,SIM,03/06/2016,11,1,NÃO
5894,44796,44796,44796,44796,44796,ACIDENTE,-81.522.222.222,349.094.444.444,RECIFE,PE,...,2011-07-13,09:54:00,SIM,FINALIZADA,A-019/CENIPA/2013,SIM,18/07/2013,23,1,NÃO
6040,44377,44377,44377,44377,44377,ACIDENTE,-215.997.222.222,-488.327.777.778,ITÁPOLIS,SP,...,2011-04-09,14:50:00,SIM,FINALIZADA,A-089/CENIPA/2012,SIM,29/08/2012,11,1,NÃO
6238,43471,43471,43471,43471,43471,ACIDENTE,-235.297.222.222,-466.319.444.444,SÃO PAULO,SP,...,2010-12-14,20:15:00,SIM,FINALIZADA,A-042/CENIPA/2011,SIM,21/07/2011,11,1,NÃO
6441,42250,42250,42250,42250,42250,ACIDENTE,-229.102.777.778,-431.627.777.778,RIO DE JANEIRO,RJ,...,2010-08-12,12:26:00,SIM,FINALIZADA,A-001/CENIPA/2012,SIM,22/02/2012,19,1,SIM
6705,39992,39992,39992,39992,39992,ACIDENTE,-205.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,2010-02-17,20:07:00,SIM,FINALIZADA,A-032/CENIPA/2012,SIM,22/03/2012,11,1,SIM

In [25]:
#ocorrências com mais de 10 recomendações
filtro = df.total_recomendacoes > 10
df.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

         ocorrencia_cidade  total_recomendacoes
2836               VITÓRIA                   12
3970                SANTOS                   13
4796              BRASÍLIA                   11
5705            UBERLÂNDIA                   20
5885  SÃO JOSÉ DOS PINHAIS                   11
5894                RECIFE                   23
6040              ITÁPOLIS                   11
6238             SÃO PAULO                   11
6441        RIO DE JANEIRO                   19
6705             SÃO PAULO                   11

In [26]:
#ocorrências cuja classificação == INCIDENTE GRAVE	
filtro = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
8,81009,81009,81009,81009,81009,INCIDENTE GRAVE,NaN,NaN,NAVIRAÍ,MS,...,2022-10-01,10:10:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
10,81017,81017,81017,81017,81017,INCIDENTE GRAVE,NaN,NaN,GOIÂNIA,GO,...,2022-09-30,13:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
13,81003,81003,81003,81003,81003,INCIDENTE GRAVE,NaN,NaN,ARAÇATUBA,SP,...,2022-09-26,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6733,39487,39487,39487,39487,39487,INCIDENTE GRAVE,-10.290.000,-48.357.778,PALMAS,TO,...,2010-01-26,16:50:00,SIM,FINALIZADA,IG-575/CENIPA/2014,SIM,13/10/2014,0,1,NÃO
6739,39709,39709,39709,39709,39709,INCIDENTE GRAVE,\t-25.40333333\t,\t-49.23361111\t,CURITIBA,PR,...,2010-01-23,16:36:00,***,FINALIZADA,IG-029/CENIPA/2011,SIM,21/07/2011,2,1,SIM
6756,39156,39156,39156,39156,39156,INCIDENTE GRAVE,-152.402.777.778,-593.541.666.667,CASCAVEL,PR,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,30/06/2011,2,1,NÃO
6757,39711,39711,39711,39711,39711,INCIDENTE GRAVE,***,***,PARÁ DE MINAS,MG,...,2010-01-10,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6761,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-65.319.444.444,-643.805.555.556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,21/07/2011,3,1,NÃO

In [27]:
#ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro1 = df.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
13,81003,81003,81003,81003,81003,INCIDENTE GRAVE,NaN,NaN,ARAÇATUBA,SP,...,2022-09-26,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
53,80951,80951,80951,80951,80951,INCIDENTE GRAVE,NaN,NaN,ASSIS,SP,...,2022-08-31,18:45:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
69,80925,80925,80925,80925,80925,INCIDENTE GRAVE,-23.508.989,-46.638.352,SÃO PAULO,SP,...,2022-08-20,19:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6455,42323,42323,42323,42323,42323,INCIDENTE GRAVE,***,***,SÃO JOSÉ DO RIO PRETO,SP,...,2010-08-05,12:01:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
6470,42289,42289,42289,42289,42289,INCIDENTE GRAVE,-235.075,-466.344.444.444,SÃO PAULO,SP,...,2010-07-29,20:06:00,SIM,FINALIZADA,IG-510/CENIPA/2015,SIM,03/06/2015,0,1,NÃO
6548,41411,41411,41411,41411,41411,INCIDENTE GRAVE,-235.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,2010-06-08,19:30:00,SIM,FINALIZADA,IG-020/CENIPA/2011,SIM,30/06/2011,2,1,SIM
6595,40620,40620,40620,40620,40620,INCIDENTE GRAVE,***,***,GUARULHOS,SP,...,2010-05-06,15:50:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
6631,40270,40270,40270,40270,40270,INCIDENTE GRAVE,***,***,PIRASSUNUNGA,SP,...,2010-04-15,20:15:00,SIM,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO

In [28]:
#ocorrências cuja (classificação == INCIDENTE GRAVE ou classificação == INCIDENTE) e o estado == SP
filtro1 = df.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = df.ocorrencia_uf == 'SP'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,2022-10-09,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
13,81003,81003,81003,81003,81003,INCIDENTE GRAVE,NaN,NaN,ARAÇATUBA,SP,...,2022-09-26,18:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
14,81001,81001,81001,81001,81001,INCIDENTE,NaN,NaN,BRAGANÇA PAULISTA,SP,...,2022-09-25,20:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
18,80997,80997,80997,80997,80997,INCIDENTE,NaN,NaN,GUARULHOS,SP,...,2022-09-21,11:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6736,39848,39848,39848,39848,39848,INCIDENTE,NaN,NaN,GUARULHOS,SP,...,2010-01-25,17:05:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6741,39768,39768,39768,39768,39768,INCIDENTE,NaN,NaN,CAMPINAS,SP,...,2010-01-21,20:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6743,39847,39847,39847,39847,39847,INCIDENTE,NaN,NaN,SOROCABA,SP,...,2010-01-20,13:10:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6751,39809,39809,39809,39809,39809,INCIDENTE,NaN,NaN,SÃO PAULO,SP,...,2010-01-15,15:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6753,39828,39828,39828,39828,39828,INCIDENTE,***,***,SANTOS,SP,...,2010-01-15,17:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [29]:
#ocorrências cuja cidade comecem com a letra C
filtro = df.ocorrencia_cidade.str[0] == 'C'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
22,80996,80996,80996,80996,80996,INCIDENTE,NaN,NaN,CAMPO LARGO,PR,...,2022-09-20,18:17:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
23,80994,80994,80994,80994,80994,INCIDENTE,NaN,NaN,CURITIBA,PR,...,2022-09-19,18:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
27,80987,80987,80987,80987,80987,INCIDENTE,NaN,NaN,CONFINS,MG,...,2022-09-15,15:12:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
28,80988,80988,80988,80988,80988,INCIDENTE GRAVE,NaN,NaN,CACHOEIRA DO ARARI,PA,...,2022-09-15,16:20:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
33,80981,80981,80981,80981,80981,INCIDENTE,NaN,NaN,CANTÁ,RR,...,2022-09-11,13:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6748,40310,40310,40310,40310,40310,INCIDENTE,NaN,NaN,CRUZEIRO DO SUL,AC,...,2010-01-18,19:32:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6750,39315,39315,39315,39315,39315,ACIDENTE,-6.615,-641.116.666.667,CANUTAMA,AM,...,2010-01-15,21:22:00,SIM,FINALIZADA,A-519/CENIPA/2016,SIM,08/02/2017,0,1,NÃO
6756,39156,39156,39156,39156,39156,INCIDENTE GRAVE,-152.402.777.778,-593.541.666.667,CASCAVEL,PR,...,2010-01-10,23:15:00,SIM,FINALIZADA,I-004/CENIPA/2011,SIM,30/06/2011,2,1,NÃO
6761,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-65.319.444.444,-643.805.555.556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,21/07/2011,3,1,NÃO
6762,40215,40215,40215,40215,40215,INCIDENTE,***,***,COARI,AM,...,2010-01-07,18:40:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,SIM

In [30]:
#ocorrências cuja cidade terminam com a letra A
filtro = df.ocorrencia_cidade.str[-1] == 'A'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,2022-10-09,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,2022-10-06,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
10,81017,81017,81017,81017,81017,INCIDENTE GRAVE,NaN,NaN,GOIÂNIA,GO,...,2022-09-30,13:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM
11,81006,81006,81006,81006,81006,INCIDENTE,NaN,NaN,UBERLÂNDIA,MG,...,2022-09-28,12:55:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
12,81014,81014,81014,81014,81014,ACIDENTE,NaN,NaN,BOA VISTA,RR,...,2022-09-27,00:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6742,39772,39772,39772,39772,39772,INCIDENTE,NaN,NaN,UBERLÂNDIA,MG,...,2010-01-20,18:58:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6743,39847,39847,39847,39847,39847,INCIDENTE,NaN,NaN,SOROCABA,SP,...,2010-01-20,13:10:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6750,39315,39315,39315,39315,39315,ACIDENTE,-6.615,-641.116.666.667,CANUTAMA,AM,...,2010-01-15,21:22:00,SIM,FINALIZADA,A-519/CENIPA/2016,SIM,08/02/2017,0,1,NÃO
6760,40414,40414,40414,40414,40414,INCIDENTE,NaN,NaN,BRASÍLIA,DF,...,2010-01-10,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
6761,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-65.319.444.444,-643.805.555.556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,21/07/2011,3,1,NÃO

In [31]:
#ocorrências cuja cidade terminam com os caracteres MA
filtro = df.ocorrencia_cidade.str[-2:] == 'MA'
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
286,80671,80671,80671,80671,80671,INCIDENTE GRAVE,2.726.944,-62.950.556,IRACEMA,RR,...,2022-04-21,20:00:00,SIM,ATIVA,IG-055/CENIPA/2022,NÃO,NaN,0,1,SIM
296,80648,80648,80648,80648,80648,INCIDENTE GRAVE,-1.216.833,-4.322.250,IBOTIRAMA,BA,...,2022-04-15,14:25:00,SIM,ATIVA,IG-048/CENIPA/2022,NÃO,NaN,0,1,SIM
321,80632,80632,80632,80632,80632,INCIDENTE,-22.575,-4.212.388.888.888,ARARUAMA,RJ,...,2022-04-03,13:25:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
672,80252,80252,80252,80252,80252,ACIDENTE,2.548.333,-62.727.500,IRACEMA,RR,...,2021-08-04,11:45:00,SIM,FINALIZADA,A-094/CENIPA/2021,SIM,21/09/2022,1,1,NÃO
674,80227,80227,80227,80227,80227,ACIDENTE,-23.638.333,-53.555.278,UMUARAMA,PR,...,2021-08-02,14:30:00,SIM,ATIVA,A-093/CENIPA/2021,NÃO,NaN,0,1,NÃO
904,79943,79943,79943,79943,79943,INCIDENTE,-1.216.444,-4.322.555,IBOTIRAMA,BA,...,2021-03-03,11:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
990,79820,79820,79820,79820,79820,INCIDENTE,"-20,047222","-43,961388",NOVA LIMA,MG,...,2021-01-14,09:27:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
992,79830,79830,79830,79830,79830,INCIDENTE,-200.472,-4.396.138,NOVA LIMA,MG,...,2021-01-14,09:27:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1009,79823,79823,79823,79823,79823,ACIDENTE,2.572.880,-63.788.730,IRACEMA,RR,...,2021-01-05,20:07:00,SIM,ATIVA,A-003/CENIPA/2021,NÃO,NaN,0,1,NÃO
1296,79400,79400,79400,79400,79400,INCIDENTE,\t-26.96587675\t,\t-49.51727374\t,IBIRAMA,SC,...,2020-06-09,14:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1322,79338,79338,79338,79338,79338,INCIDENTE,-22.321.944,-53.777.778,IVINHEMA,MS,...,2020-05-15,09:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1362,79282,79282,79282,79282,79282,ACIDENTE,-19.712.364.768,-504.727.263.643,ITURAMA,MG,...,2020-04-11,12:20:00,SIM,ATIVA,A-048/CENIPA/2020,NÃO,NaN,0,1,NÃO
1684,78782,78782,78782,78782,78782,ACIDENTE,-22.296.944,-53.849.167,IVINHEMA,MS,...,2019-09-08,17:45:00,SIM,ATIVA,A-129/CENIPA/2019,NÃO,NaN,0,1,NÃO
1695,78923,78923,78923,78923,78923,INCIDENTE GRAVE,-65.291.666,-64.383.888,CANUTAMA,AM,...,2019-09-03,14:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1779,78867,78867,78867,78867,78867,INCIDENTE,***,***,IRACEMA,RR,...,2019-07-06,00:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
2189,78080,78080,78080,78080,78080,ACIDENTE,***,***,ITAPEMA,SC,...,2018-07-28,14:20:00,SIM,FINALIZADA,A-140/CENIPA/2018,SIM,28/06/2019,0,1,NÃO
2454,77612,77612,77612,77612,77612,ACIDENTE,\t-27.12\t,\t-48.64694444\t,ITAPEMA,SC,...,2018-01-06,10:30:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO
2535,77371,77371,77371,77371,77371,ACIDENTE,-65.291.666.667,-643.838.888.88,CANUTAMA,AM,...,2017-11-02,19:30:00,SIM,FINALIZADA,A-137/CENIPA/2017,SIM,27/07/2018,1,1,SIM
2884,66265,66265,66265,66265,66265,ACIDENTE,-212.772.222.222,-503.944.444.444,BURITAMA,SP,...,2017-01-13,16:00:00,SIM,FINALIZADA,A-009/CENIPA/2017,SIM,27/10/2017,0,1,NÃO
3041,65633,65633,65633,65633,65633,INCIDENTE GRAVE,-201.675,-4.389.333,NOVA LIMA,MG,...,2016-08-31,17:40:00,SIM,ATIVA,IG-114/CENIPA/2016,NÃO,NaN,0,1,NÃO
3083,65414,65414,65414,65414,65414,INCIDENTE GRAVE,-200.472.222.222,-439.613.888.889,NOVA LIMA,MG,...,2016-07-08,19:50:00,SIM,FINALIZADA,IG-099/CENIPA/2016,SIM,10/05/2018,1,1,NÃO
3579,53271,53271,53271,53271,53271,INCIDENTE GRAVE,\t-23.79583333\t,\t-53.47972222\t,UMUARAMA,PR,...,2015-05-17,17:00:00,SIM,FINALIZADA,IG-074/CENIPA/2015,SIM,23/06/2016,0,1,NÃO
3594,53265,53265,53265,53265,53265,ACIDENTE,-45.577.777.778,-607.861.111.111,PACARAIMA,RR,...,2015-05-05,16:05:00,SIM,FINALIZADA,A-067/CENIPA/2015,SIM,28/10/2016,2,1,SIM
3609,53223,53223,53223,53223,53223,ACIDENTE,-212.033.333.333,-488.480.555.556,PINDORAMA,SP,...,2015-04-22,12:45:00,SIM,FINALIZADA,A-062/CENIPA/2015,SIM,16/06/2016,0,1,NÃO
3676,53596,53596,53596,53596,53596,INCIDENTE,\t-27.13638889\t,\t-48.68166667\t,ITAPEMA,SC,...,2015-03-10,21:35:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3725,52984,52984,52984,52984,52984,ACIDENTE,-200.486.111.111,-439.605.555.556,NOVA LIMA,MG,...,2015-02-01,15:10:00,***,FINALIZADA,A-015/CENIPA/2015,SIM,22/04/2016,0,1,NÃO
3767,52979,52979,52979,52979,52979,ACIDENTE,-223.855.555.556,-538.763.888.889,IVINHEMA,MS,...,2015-01-02,14:50:00,***,FINALIZADA,A-002/CENIPA/2015,SIM,25/06/2018,0,1,NÃO
3800,52832,52832,52832,52832,52832,ACIDENTE,-210.919.444.444,-502.280.555.556,BURITAMA,SP,...,2014-12-14,23:40:00,SIM,FINALIZADA,A-199/CENIPA/2014,SIM,19/10/2015,0,1,NÃO
3910,52340,52340,52340,52340,52340,ACIDENTE,-214.041.666.667,-458.263.888.889,FAMA,MG,...,2014-09-20,15:00:00,SIM,FINALIZADA,A-158/CENIPA/2014,SIM,07/11/2018,1,1,NÃO
4110,51347,51347,51347,51347,51347,INCIDENTE,NaN,NaN,DIADEMA,SP,...,2014-05-04,16:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4123,80059,80059,80059,80059,80059,INCIDENTE,-22.295.556,-53.848.889,IVINHEMA,MS,...,2014-04-27,11:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
4663,48799,48799,48799,48799,48799,ACIDENTE,-65.341.666.667,-64.385,CANUTAMA,AM,...,2013-06-18,21:30:00,SIM,FINALIZADA,A-114/CENIPA/2013,SIM,09/07/2013,0,1,SIM
4672,49113,49113,49113,49113,49113,INCIDENTE GRAVE,-200.108.333.333,-439.666.666.667,NOVA LIMA,MG,...,2013-06-15,12:00:00,SIM,FINALIZADA,IG-129/CENIPA/2013,SIM,16/06/2014,4,1,NÃO
5368,46180,46180,46180,46180,46180,ACIDENTE,-207.419.444.444,-505.316.666.667,AURIFLAMA,SP,...,2012-06-16,19:30:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
5391,45939,45939,45939,45939,45939,ACIDENTE,\t-23.76944444\t,\t-53.41944444\t,UMUARAMA,PR,...,2012-05-30,19:00:00,***,FINALIZADA,ENCERRADA NO RAI,NÃO,NaN,0,1,NÃO
5733,51785,51785,51785,51785,51785,INCIDENTE,NaN,NaN,BURITAMA,SP,...,2011-10-25,19:15:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6080,44198,44198,44198,44198,44198,ACIDENTE,***,***,BURITAMA,SP,...,2011-03-19,11:18:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6361,43062,43062,43062,43062,43062,ACIDENTE,-160.802.777.778,-480.652.777.778,NOVO GAMA,GO,...,2010-09-25,16:30:00,SIM,FINALIZADA,A-596/CENIPA/2014,SIM,01/10/2014,1,1,NÃO
6750,39315,39315,39315,39315,39315,ACIDENTE,-6.615,-641.116.666.667,CANUTAMA,AM,...,2010-01-15,21:22:00,SIM,FINALIZADA,A-519/CENIPA/2016,SIM,08/02/2017,0,1,NÃO
6761,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-65.319.444.444,-643.805.555.556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,21/07/2011,3,1,NÃO

In [32]:
#ocorrências cuja cidade contém (em qualquer parte do conteúdo) os caracteres MA ou AL
filtro = df.ocorrencia_cidade.str.contains('MA|AL')
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
4,81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,...,2022-10-05,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
5,81019,81019,81019,81019,81019,ACIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2022-10-03,20:50:00,NÃO,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
19,80998,80998,80998,80998,80998,ACIDENTE,NaN,NaN,ENGENHEIRO CALDAS,MG,...,2022-09-21,17:51:00,NÃO,ATIVA,A-107/CENIPA/2022,NÃO,NaN,0,1,NÃO
34,80969,80969,80969,80969,80969,INCIDENTE,NaN,NaN,MARABÁ,PA,...,2022-09-10,17:45:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
37,80979,80979,80979,80979,80979,ACIDENTE,NaN,NaN,ALTO ARAGUAIA,MT,...,2022-09-10,22:00:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6750,39315,39315,39315,39315,39315,ACIDENTE,-6.615,-641.116.666.667,CANUTAMA,AM,...,2010-01-15,21:22:00,SIM,FINALIZADA,A-519/CENIPA/2016,SIM,08/02/2017,0,1,NÃO
6752,39810,39810,39810,39810,39810,INCIDENTE,***,***,SALVADOR,BA,...,2010-01-15,18:23:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
6755,39507,39507,39507,39507,39507,ACIDENTE,-155.588.888.889,-543.047.222.222,PRIMAVERA DO LESTE,MT,...,2010-01-11,17:00:00,SIM,FINALIZADA,A-016/CENIPA/2011,SIM,30/06/2011,2,1,NÃO
6761,39707,39707,39707,39707,39707,INCIDENTE GRAVE,-65.319.444.444,-643.805.555.556,CANUTAMA,AM,...,2010-01-09,12:30:00,SIM,FINALIZADA,IG-028/CENIPA/2011,SIM,21/07/2011,3,1,NÃO
6763,39807,39807,39807,39807,39807,INCIDENTE,***,***,SALVADOR,BA,...,2010-01-06,17:53:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO

In [33]:
#ocorrências do ano de 2015
filtro = df.ocorrencia_dia.dt.year == 2015
df.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
3300,60649,60649,60649,60649,60649,ACIDENTE,-271.633.333.333,-486.258.333.333,PORTO BELO,SC,...,2015-12-31,14:00:00,SIM,FINALIZADA,A - 501/CENIPA/2018,SIM,25/06/2018,0,1,SIM
3301,60631,60631,60631,60631,60631,ACIDENTE,\t-29.1625\t,\t-55.93888889\t,MAÇAMBARÁ,RS,...,2015-12-28,19:00:00,SIM,FINALIZADA,A-172/CENIPA/2015,SIM,27/07/2018,2,1,NÃO
3302,60642,60642,60642,60642,60642,INCIDENTE,\t-26.21916667\t,\t-48.50027778\t,SÃO FRANCISCO DO SUL,SC,...,2015-12-26,16:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3303,60600,60600,60600,60600,60600,INCIDENTE,-57.688.888.889,-353.663.888.889,GUARULHOS,SP,...,2015-12-25,19:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3304,60632,60632,60632,60632,60632,INCIDENTE GRAVE,-238.441.666.667,-490.569.444.444,ITABERÁ,SP,...,2015-12-24,14:00:00,NaN,FINALIZADA,IG-171/CENIPA/2015,SIM,01/08/2017,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3766,52976,52976,52976,52976,52976,ACIDENTE,-2.475.333.333,-53.635,TOLEDO,PR,...,2015-01-04,22:04:00,SIM,FINALIZADA,A-003/CENIPA/2015,SIM,16/06/2016,6,1,NÃO
3767,52979,52979,52979,52979,52979,ACIDENTE,-223.855.555.556,-538.763.888.889,IVINHEMA,MS,...,2015-01-02,14:50:00,***,FINALIZADA,A-002/CENIPA/2015,SIM,25/06/2018,0,1,NÃO
3768,53073,53073,53073,53073,53073,INCIDENTE,NaN,NaN,TEFÉ,AM,...,2015-01-02,16:28:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3769,53074,53074,53074,53074,53074,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,2015-01-02,20:34:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3770,52992,52992,52992,52992,52992,INCIDENTE GRAVE,***,***,SALVADOR,BA,...,2015-01-01,11:40:00,***,FINALIZADA,IG-001/CENIPA/2015,SIM,07/11/2018,3,2,NÃO

In [34]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

In [35]:
#ocorrências do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia.dt.year == 2015
filtro_mes = df.ocorrencia_dia.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia.dt.day > 2 
filtro_dia_fim = df.ocorrencia_dia.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
3327,53628,53628,53628,53628,53628,ACIDENTE,-220.327.777.778,-470.258.333.333,AGUAÍ,SP,...,2015-12-08,14:30:00,NaN,FINALIZADA,A-161/CENIPA/2015,SIM,17/05/2018,1,1,NÃO
3328,53629,53629,53629,53629,53629,INCIDENTE GRAVE,-202.991.666.667,-505.469.444.444,JALES,SP,...,2015-12-08,10:20:00,NaN,FINALIZADA,A-162/CENIPA/2015,NÃO,NaN,0,1,NÃO
3329,53631,53631,53631,53631,53631,INCIDENTE,-230.069.444.444,-471.344.444.444,CAMPINAS,SP,...,2015-12-08,16:19:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3330,60636,60636,60636,60636,60636,INCIDENTE,\t-29.19555556\t,\t-51.18972222\t,CAXIAS DO SUL,RS,...,2015-12-08,13:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3331,53625,53625,53625,53625,53625,ACIDENTE,-166.533.333.333,-496.094.444.444,TRINDADE,GO,...,2015-12-06,13:10:00,NaN,FINALIZADA,A-159/CENIPA/2015,SIM,08/04/2019,3,1,NÃO
3332,53626,53626,53626,53626,53626,ACIDENTE,-227.555.555.556,-472.672.222.222,AMERICANA,SP,...,2015-12-06,15:00:00,NaN,FINALIZADA,A-160/CENIPA/2015,SIM,28/10/2019,1,1,SIM
3333,53575,53575,53575,53575,53575,INCIDENTE,-220.366.666.667,-410.708.333.333,CAMPOS DOS GOYTACAZES,RJ,...,2015-12-03,10:50:00,NaN,FINALIZADA,***,NÃO,NaN,0,1,NÃO
3334,60637,60637,60637,60637,60637,INCIDENTE,-19.91,-439.902.777.778,BELO HORIZONTE,MG,...,2015-12-03,16:47:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [36]:
df['ocorrencia_dia_hora'] = pd.to_datetime(df.ocorrencia_dia.astype(str) + ' '  + df.ocorrencia_hora)

In [37]:
df.head()

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
0,81027,81027,81027,81027,81027,INCIDENTE GRAVE,NaN,NaN,SÃO PAULO,SP,...,16:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,SIM,2022-10-09 16:30:00
1,81030,81030,81030,81030,81030,INCIDENTE,NaN,NaN,VITÓRIA,ES,...,16:20:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO,2022-10-09 16:20:00
2,81023,81023,81023,81023,81023,INCIDENTE GRAVE,NaN,NaN,AMERICANA,SP,...,15:30:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,SIM,2022-10-06 15:30:00
3,81029,81029,81029,81029,81029,INCIDENTE,NaN,NaN,BELO HORIZONTE,MG,...,00:44:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2022-10-06 00:44:00
4,81025,81025,81025,81025,81025,INCIDENTE,NaN,NaN,MANAUS,AM,...,20:56:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2022-10-05 20:56:00

In [38]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
ocorrencia_dia_hora               datetime64[ns]
dtype: object

In [39]:
#ocorrências do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = df.ocorrencia_dia_hora.dt.year == 2015
filtro_mes = df.ocorrencia_dia_hora.dt.month == 12
filtro_dia_inicio = df.ocorrencia_dia_hora.dt.day > 2 
filtro_dia_fim = df.ocorrencia_dia_hora.dt.day < 9
df.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
3327,53628,53628,53628,53628,53628,ACIDENTE,-220.327.777.778,-470.258.333.333,AGUAÍ,SP,...,14:30:00,NaN,FINALIZADA,A-161/CENIPA/2015,SIM,17/05/2018,1,1,NÃO,2015-12-08 14:30:00
3328,53629,53629,53629,53629,53629,INCIDENTE GRAVE,-202.991.666.667,-505.469.444.444,JALES,SP,...,10:20:00,NaN,FINALIZADA,A-162/CENIPA/2015,NÃO,NaN,0,1,NÃO,2015-12-08 10:20:00
3329,53631,53631,53631,53631,53631,INCIDENTE,-230.069.444.444,-471.344.444.444,CAMPINAS,SP,...,16:19:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-08 16:19:00
3330,60636,60636,60636,60636,60636,INCIDENTE,\t-29.19555556\t,\t-51.18972222\t,CAXIAS DO SUL,RS,...,13:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-08 13:00:00
3331,53625,53625,53625,53625,53625,ACIDENTE,-166.533.333.333,-496.094.444.444,TRINDADE,GO,...,13:10:00,NaN,FINALIZADA,A-159/CENIPA/2015,SIM,08/04/2019,3,1,NÃO,2015-12-06 13:10:00
3332,53626,53626,53626,53626,53626,ACIDENTE,-227.555.555.556,-472.672.222.222,AMERICANA,SP,...,15:00:00,NaN,FINALIZADA,A-160/CENIPA/2015,SIM,28/10/2019,1,1,SIM,2015-12-06 15:00:00
3333,53575,53575,53575,53575,53575,INCIDENTE,-220.366.666.667,-410.708.333.333,CAMPOS DOS GOYTACAZES,RJ,...,10:50:00,NaN,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-03 10:50:00
3334,60637,60637,60637,60637,60637,INCIDENTE,-19.91,-439.902.777.778,BELO HORIZONTE,MG,...,16:47:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-03 16:47:00

In [40]:
filtro1 = df.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = df.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
df.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
3327,53628,53628,53628,53628,53628,ACIDENTE,-220.327.777.778,-470.258.333.333,AGUAÍ,SP,...,14:30:00,NaN,FINALIZADA,A-161/CENIPA/2015,SIM,17/05/2018,1,1,NÃO,2015-12-08 14:30:00
3328,53629,53629,53629,53629,53629,INCIDENTE GRAVE,-202.991.666.667,-505.469.444.444,JALES,SP,...,10:20:00,NaN,FINALIZADA,A-162/CENIPA/2015,NÃO,NaN,0,1,NÃO,2015-12-08 10:20:00
3330,60636,60636,60636,60636,60636,INCIDENTE,\t-29.19555556\t,\t-51.18972222\t,CAXIAS DO SUL,RS,...,13:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-08 13:00:00
3331,53625,53625,53625,53625,53625,ACIDENTE,-166.533.333.333,-496.094.444.444,TRINDADE,GO,...,13:10:00,NaN,FINALIZADA,A-159/CENIPA/2015,SIM,08/04/2019,3,1,NÃO,2015-12-06 13:10:00
3332,53626,53626,53626,53626,53626,ACIDENTE,-227.555.555.556,-472.672.222.222,AMERICANA,SP,...,15:00:00,NaN,FINALIZADA,A-160/CENIPA/2015,SIM,28/10/2019,1,1,SIM,2015-12-06 15:00:00
3334,60637,60637,60637,60637,60637,INCIDENTE,-19.91,-439.902.777.778,BELO HORIZONTE,MG,...,16:47:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-12-03 16:47:00

In [41]:
#ocorrências do ano de 2015 e mês 03
filtro1 = df.ocorrencia_dia.dt.year == 2015
filtro2 = df.ocorrencia_dia.dt.month == 3
df201503 = df.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
3644,53211,53211,53211,53211,53211,INCIDENTE,-223.436.111.111,-490.538.888.889,BAURU,SP,...,19:40:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-30 19:40:00
3645,53181,53181,53181,53181,53181,ACIDENTE,-107.555.555.556,-554.583.333.333,COLÍDER,MT,...,20:17:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,2015-03-29 20:17:00
3646,53187,53187,53187,53187,53187,INCIDENTE,\t-26.22111111\t,\t-48.80194444\t,JOINVILLE,SC,...,18:36:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-29 18:36:00
3647,53179,53179,53179,53179,53179,ACIDENTE,-171.741.666.667,-516.755.555.556,CAIAPÔNIA,GO,...,10:30:00,SIM,FINALIZADA,A-047/CENIPA/2015,SIM,03/06/2016,0,1,NÃO,2015-03-28 10:30:00
3648,53180,53180,53180,53180,53180,ACIDENTE,-186.233.333.333,-481.636.111.111,ARAGUARI,MG,...,18:52:00,SIM,FINALIZADA,A-048/CENIPA/2015,SIM,07/07/2016,0,1,NÃO,2015-03-28 18:52:00
3649,53190,53190,53190,53190,53190,INCIDENTE,NaN,NaN,CAMPINAS,SP,...,16:26:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-28 16:26:00
3650,53212,53212,53212,53212,53212,INCIDENTE,NaN,NaN,JUNDIAÍ,SP,...,17:32:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-28 17:32:00
3651,53213,53213,53213,53213,53213,INCIDENTE,NaN,NaN,JUNDIAÍ,SP,...,15:51:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-28 15:51:00
3652,53186,53186,53186,53186,53186,INCIDENTE,NaN,NaN,BRASÍLIA,DF,...,14:55:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-27 14:55:00
3653,53194,53194,53194,53194,53194,ACIDENTE,-41.641.666.667,-407.847.222.222,GUARACIABA DO NORTE,CE,...,20:30:00,SIM,FINALIZADA,A-046/CENIPA/2015,SIM,23/06/2016,0,1,SIM,2015-03-26 20:30:00
3654,53166,53166,53166,53166,53166,INCIDENTE GRAVE,-116.711.111.111,-457.208.333.333,RIACHÃO DAS NEVES,BA,...,14:45:00,SIM,FINALIZADA,IG-044/CENIPA/2015,SIM,19/10/2015,0,1,NÃO,2015-03-24 14:45:00
3655,53170,53170,53170,53170,53170,INCIDENTE,NaN,NaN,CONFINS,MG,...,17:57:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-24 17:57:00
3656,53185,53185,53185,53185,53185,INCIDENTE,NaN,NaN,CURITIBA,PR,...,23:01:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-24 23:01:00
3657,53412,53412,53412,53412,53412,INCIDENTE GRAVE,0,0,MACAÉ,RJ,...,16:35:00,***,FINALIZADA,IG-045/CENIPA/2015,SIM,04/10/2021,2,1,NÃO,2015-03-24 16:35:00
3658,53178,53178,53178,53178,53178,ACIDENTE,-138.163.888.889,-571.683.333.333,DIAMANTINO,MT,...,17:15:00,SIM,FINALIZADA,A-042/CENIPA/2015,SIM,01/08/2017,0,1,NÃO,2015-03-23 17:15:00
3659,53182,53182,53182,53182,53182,ACIDENTE,-38.613.888.889,-456.544.444.444,SANTA LUZIA,MA,...,20:40:00,SIM,FINALIZADA,A-043/CENIPA/2015,SIM,19/12/2018,0,1,NÃO,2015-03-23 20:40:00
3660,53184,53184,53184,53184,53184,ACIDENTE,\t-26.24277778\t,\t-51.07444444\t,PORTO UNIÃO,SC,...,13:44:00,SIM,NaN,NaN,NÃO,NaN,0,1,NÃO,2015-03-22 13:44:00
3661,53165,53165,53165,53165,53165,INCIDENTE GRAVE,-126.108.333.333,-462.463.888.889,SÃO DESIDÉRIO,BA,...,14:35:00,SIM,FINALIZADA,IG-041/CENIPA/2015,SIM,16/11/2015,0,1,NÃO,2015-03-20 14:35:00
3662,53188,53188,53188,53188,53188,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,21:00:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-20 21:00:00
3663,53169,53169,53169,53169,53169,INCIDENTE,NaN,NaN,BELÉM,PA,...,03:25:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-19 03:25:00
3664,53151,53151,53151,53151,53151,INCIDENTE GRAVE,-33.736.111.111,-577.247.222.222,MAUÉS,AM,...,18:07:00,SIM,FINALIZADA,IG-040/CENIPA/2015,SIM,11/03/2019,1,1,SIM,2015-03-16 18:07:00
3665,53168,53168,53168,53168,53168,INCIDENTE,NaN,NaN,PARÁ DE MINAS,MG,...,21:05:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-16 21:05:00
3666,53164,53164,53164,53164,53164,ACIDENTE,-77.180.555.556,-379.269.444.444,PRINCESA ISABEL,PB,...,18:30:00,SIM,FINALIZADA,A-039/CENIPA/2015,SIM,19/10/2015,0,1,NÃO,2015-03-15 18:30:00
3667,53189,53189,53189,53189,53189,INCIDENTE,NaN,NaN,CONFINS,MG,...,07:20:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-14 07:20:00
3668,53193,53193,53193,53193,53193,ACIDENTE,-130.891.666.667,-525.105.555.556,CANARANA,MT,...,18:00:00,***,FINALIZADA,A-038/CENIPA/2015,SIM,16/11/2015,0,1,NÃO,2015-03-14 18:00:00
3669,53153,53153,53153,53153,53153,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,15:45:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-13 15:45:00
3670,53154,53154,53154,53154,53154,INCIDENTE,NaN,NaN,SOROCABA,SP,...,14:40:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-13 14:40:00
3671,53238,53238,53238,53238,53238,INCIDENTE,NaN,NaN,SERRA,ES,...,11:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-13 11:30:00
3672,53148,53148,53148,53148,53148,ACIDENTE,-223.388.888.889,-473.580.555.556,ARARAS,SP,...,12:40:00,***,FINALIZADA,A-037/CENIPA/2015,SIM,19/10/2015,0,1,NÃO,2015-03-12 12:40:00
3673,53149,53149,53149,53149,53149,ACIDENTE,-42.597.222.222,-699.169.444.444,TABATINGA,AM,...,23:25:00,SIM,FINALIZADA,A-036/CENIPA/2015,SIM,14/10/2016,0,1,NÃO,2015-03-11 23:25:00
3674,53152,53152,53152,53152,53152,INCIDENTE GRAVE,-229.938.888.889,-433.752.777.778,RIO DE JANEIRO,RJ,...,11:30:00,***,FINALIZADA,IG-035/CENIPA/2015,SIM,26/08/2016,2,1,NÃO,2015-03-10 11:30:00
3675,53167,53167,53167,53167,53167,INCIDENTE,NaN,NaN,MARABÁ,PA,...,17:33:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-10 17:33:00
3676,53596,53596,53596,53596,53596,INCIDENTE,\t-27.13638889\t,\t-48.68166667\t,ITAPEMA,SC,...,21:35:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2015-03-10 21:35:00
3677,53112,53112,53112,53112,53112,ACIDENTE,-222.036.111.111,-471.966.666.667,MOGI GUAÇU,SP,...,21:00:00,***,FINALIZADA,A-034/CENIPA/2015,SIM,17/09/2021,1,1,NÃO,2015-03-06 21:00:00
3678,53109,53109,53109,53109,53109,ACIDENTE,-205.994.444.444,-546.025,CAMPO GRANDE,MS,...,13:50:00,SIM,FINALIZADA,A-033/CENIPA/2015,SIM,24/09/2018,0,1,NÃO,2015-03-05 13:50:00
3679,53120,53120,53120,53120,53120,ACIDENTE,-0.2002777778,-499.672.222.222,CHAVES,PA,...,13:30:00,***,FINALIZADA,A-032/CENIPA/2015,SIM,19/10/2015,0,1,NÃO,2015-03-04 13:30:00
3680,53183,53183,53183,53183,53183,ACIDENTE,-230.819.444.444,-527.652.777.778,AMAPORÃ,PR,...,23:00:00,***,FINALIZADA,A-031/CENIPA/2015,NÃO,NaN,0,1,NÃO,2015-03-02 23:00:00

In [42]:
df201503.count()

codigo_ocorrencia                 37
codigo_ocorrencia1                37
codigo_ocorrencia2                37
codigo_ocorrencia3                37
codigo_ocorrencia4                37
ocorrencia_classificacao          37
ocorrencia_latitude               23
ocorrencia_longitude              23
ocorrencia_cidade                 37
ocorrencia_uf                     37
ocorrencia_pais                   37
ocorrencia_aerodromo              37
ocorrencia_dia                    37
ocorrencia_hora                   37
investigacao_aeronave_liberada    37
investigacao_status               35
divulgacao_relatorio_numero       35
divulgacao_relatorio_publicado    37
divulgacao_dia_publicacao         17
total_recomendacoes               37
total_aeronaves_envolvidas        37
ocorrencia_saida_pista            37
ocorrencia_dia_hora               37
dtype: int64

In [43]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [44]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: ocorrencia_aerodromo, dtype: int64

In [46]:
# contando os registros agrupado (seguro)
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [47]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [48]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [49]:
filtro1 = df.ocorrencia_dia.dt.year == 2010
filtro2 = df.ocorrencia_uf.isin(['SP','MG','ES','RJ'])
dfsudeste2010 = df.loc[filtro1 & filtro2]
dfsudeste2010

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
6217,43730,43730,43730,43730,43730,INCIDENTE,***,***,VITÓRIA,ES,...,18:10:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,2010-12-30 18:10:00
6218,43975,43975,43975,43975,43975,INCIDENTE,***,***,ARRAIAL DO CABO,RJ,...,14:28:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,2010-12-30 14:28:00
6219,43724,43724,43724,43724,43724,ACIDENTE,-227.097.222.222,-470.827.777.778,COSMÓPOLIS,SP,...,12:00:00,***,FINALIZADA,A-521/CENIPA/2014,SIM,22/08/2014,0,1,NÃO,2010-12-29 12:00:00
6224,43548,43548,43548,43548,43548,INCIDENTE,NaN,NaN,SÃO PAULO,SP,...,22:10:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,2010-12-26 22:10:00
6226,43722,43722,43722,43722,43722,ACIDENTE,***,***,CAJOBI,SP,...,11:00:00,SIM,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO,2010-12-23 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6753,39828,39828,39828,39828,39828,INCIDENTE,***,***,SANTOS,SP,...,17:45:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,2010-01-15 17:45:00
6757,39711,39711,39711,39711,39711,INCIDENTE GRAVE,***,***,PARÁ DE MINAS,MG,...,20:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO,2010-01-10 20:00:00
6759,40069,40069,40069,40069,40069,ACIDENTE,-235.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,19/11/2012,8,1,NÃO,2010-01-10 14:50:00
6766,40211,40211,40211,40211,40211,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,12:00:00,SIM,FINALIZADA,***,NÃO,NaN,0,1,NÃO,2010-01-03 12:00:00
6768,40351,40351,40351,40351,40351,INCIDENTE,NaN,NaN,RIO DE JANEIRO,RJ,...,03:00:00,SIM,FINALIZADA,NaN,NÃO,NaN,0,1,NÃO,2010-01-03 03:00:00

In [50]:
dfsudeste2010.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE            39
INCIDENTE          171
INCIDENTE GRAVE     18
dtype: int64

In [51]:
dfsudeste2010.count()

codigo_ocorrencia                 228
codigo_ocorrencia1                228
codigo_ocorrencia2                228
codigo_ocorrencia3                228
codigo_ocorrencia4                228
ocorrencia_classificacao          228
ocorrencia_latitude                81
ocorrencia_longitude               81
ocorrencia_cidade                 228
ocorrencia_uf                     228
ocorrencia_pais                   228
ocorrencia_aerodromo              228
ocorrencia_dia                    228
ocorrencia_hora                   228
investigacao_aeronave_liberada    228
investigacao_status               202
divulgacao_relatorio_numero        50
divulgacao_relatorio_publicado    228
divulgacao_dia_publicacao          29
total_recomendacoes               228
total_aeronaves_envolvidas        228
ocorrencia_saida_pista            228
ocorrencia_dia_hora               228
dtype: int64

In [52]:
dfsudeste2010.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
ES             INCIDENTE                    5
MG             ACIDENTE                     7
               INCIDENTE                   39
               INCIDENTE GRAVE              5
RJ             ACIDENTE                     9
               INCIDENTE                   52
               INCIDENTE GRAVE              4
SP             ACIDENTE                    23
               INCIDENTE                   75
               INCIDENTE GRAVE              9
dtype: int64

In [53]:
dfsudeste2010.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
RIO DE JANEIRO           47
SÃO PAULO                33
GUARULHOS                18
BELO HORIZONTE           17
CAMPINAS                 13
MACAÉ                    12
CONFINS                   7
UBERLÂNDIA                5
JUIZ DE FORA              4
VITÓRIA                   4
MARÍLIA                   3
SÃO JOSÉ DOS CAMPOS       3
SÃO JOSÉ DO RIO PRETO     3
SOROCABA                  2
ITANHAÉM                  2
RIBEIRÃO PRETO            2
IPATINGA                  2
POÇOS DE CALDAS           2
DIVINÓPOLIS               2
BAURU                     2
JUNDIAÍ                   2
ARARAQUARA                2
CAMPOS DOS GOYTACAZES     2
AREALVA                   2
MONTES CLAROS             2
UBERABA                   2
POUSO ALEGRE              1
PIRACICABA                1
PIRASSUNUNGA              1
ARRAIAL DO CABO           1
RESENDE                   1
PENÁPOLIS                 1
SANTOS                    1
SERRA NEGRA               1
SÃO BERNARDO DO CAMPO     1
TIMÓTEO                   1
ARAÇATUBA                 1
PIACATU                   1
BOM JESUS DO AMPARO       1
PARÁ DE MINAS             1
OLÍMPIA                   1
BRAGANÇA PAULISTA         1
BROTAS                    1
CAJOBI                    1
CAMANDUCAIA               1
BOITUVA                   1
CASIMIRO DE ABREU         1
BOCAINA                   1
COROMANDEL                1
COSMÓPOLIS                1
DIAMANTINA                1
BEBEDOURO                 1
IPERÓ                     1
ITÁPOLIS                  1
LINHARES                  1
MANGARATIBA               1
BOM JESUS DO GALHO        1
NOVO HORIZONTE            1
AMERICANA                 1
dtype: int64

In [55]:
filtro1 = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
filtro2 = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
6441,42250,42250,42250,42250,42250,ACIDENTE,-229.102.777.778,-431.627.777.778,RIO DE JANEIRO,RJ,...,12:26:00,SIM,FINALIZADA,A-001/CENIPA/2012,SIM,22/02/2012,19,1,SIM,2010-08-12 12:26:00
6493,41750,41750,41750,41750,41750,ACIDENTE,-229.875,-43.37,RIO DE JANEIRO,RJ,...,19:53:00,SIM,FINALIZADA,A-133/CENIPA/2011,SIM,21/12/2011,3,1,NÃO,2010-07-12 19:53:00
6649,40190,40190,40190,40190,40190,INCIDENTE,***,***,RIO DE JANEIRO,RJ,...,02:35:00,***,NaN,NaN,NÃO,NaN,3,1,NÃO,2010-04-06 02:35:00

In [56]:
filtro = dfsudeste2010.ocorrencia_cidade == 'RIO DE JANEIRO'
dfsudeste2010.loc[filtro].total_recomendacoes.sum()

25

In [57]:
dfsudeste2010.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
***     45
SBAE     0
SBAQ     0
SBBH     0
SBBP     9
SBBU     0
SBCF     0
SBGL     3
SBGR     0
SBIP     0
SBJD     7
SBJR     3
SBKP     0
SBME     0
SBMK     0
SBML     0
SBMT    27
SBPC     0
SBPR     1
SBRJ    19
SBRP     0
SBSJ     0
SBSP     0
SBSR     0
SBUL     0
SBUR     0
SBVT     0
SDAM     0
SDOI     1
SDPW     0
SDPY     0
SNDT     0
SNDV     0
SNXT     0
Name: total_recomendacoes, dtype: int64

In [58]:
dfsudeste2010.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
AMERICANA                 0
ARARAQUARA                0
ARAÇATUBA                 0
AREALVA                   0
ARRAIAL DO CABO           0
BAURU                     0
BEBEDOURO                 0
BELO HORIZONTE            2
BOCAINA                   0
BOITUVA                   1
BOM JESUS DO AMPARO       0
BOM JESUS DO GALHO        1
BRAGANÇA PAULISTA         9
BROTAS                    0
CAJOBI                    0
CAMANDUCAIA               9
CAMPINAS                  0
CAMPOS DOS GOYTACAZES     0
CASIMIRO DE ABREU         0
CONFINS                   0
COROMANDEL                0
COSMÓPOLIS                0
DIAMANTINA                0
DIVINÓPOLIS               0
GUARULHOS                 0
IPATINGA                  0
IPERÓ                     3
ITANHAÉM                  1
ITÁPOLIS                  0
JUIZ DE FORA              0
JUNDIAÍ                   7
LINHARES                  0
MACAÉ                     0
MANGARATIBA               0
MARÍLIA                   0
MONTES CLAROS             0
NOVO HORIZONTE            3
OLÍMPIA                   0
PARÁ DE MINAS             0
PENÁPOLIS                 0
PIACATU                   0
PIRACICABA                0
PIRASSUNUNGA              0
POUSO ALEGRE              0
POÇOS DE CALDAS           0
RESENDE                   8
RIBEIRÃO PRETO            0
RIO DE JANEIRO           25
SANTOS                    0
SERRA NEGRA               0
SOROCABA                  0
SÃO BERNARDO DO CAMPO     2
SÃO JOSÉ DO RIO PRETO     0
SÃO JOSÉ DOS CAMPOS       0
SÃO PAULO                41
TIMÓTEO                   3
UBERABA                   0
UBERLÂNDIA                0
VITÓRIA                   0
Name: total_recomendacoes, dtype: int64

In [59]:
filtro = dfsudeste2010.total_recomendacoes > 0
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BOITUVA                   1
BOM JESUS DO GALHO        1
ITANHAÉM                  1
BELO HORIZONTE            2
SÃO BERNARDO DO CAMPO     2
IPERÓ                     3
NOVO HORIZONTE            3
TIMÓTEO                   3
JUNDIAÍ                   7
RESENDE                   8
BRAGANÇA PAULISTA         9
CAMANDUCAIA               9
RIO DE JANEIRO           25
SÃO PAULO                41
Name: total_recomendacoes, dtype: int64

In [60]:
dfsudeste2010.loc[filtro].groupby(['ocorrencia_cidade', dfsudeste2010.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade      ocorrencia_dia
BELO HORIZONTE         2                  1
                       3                  1
BOITUVA                7                  1
BOM JESUS DO GALHO     12                 1
BRAGANÇA PAULISTA      11                 9
CAMANDUCAIA            7                  9
IPERÓ                  1                  3
ITANHAÉM               9                  1
JUNDIAÍ                5                  5
                       6                  2
NOVO HORIZONTE         7                  3
RESENDE                4                  8
RIO DE JANEIRO         4                  3
                       7                  3
                       8                 19
SÃO BERNARDO DO CAMPO  1                  2
SÃO PAULO              1                  8
                       2                 14
                       6                  2
                       11                 6
                       12                11
TIMÓTEO                2                  3
Name: total_recomendacoes, dtype: int64

In [61]:
filtro1 = dfsudeste2010.total_recomendacoes > 0
filtro2 = dfsudeste2010.ocorrencia_cidade == 'SÃO PAULO'
dfsudeste2010.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista,ocorrencia_dia_hora
6238,43471,43471,43471,43471,43471,ACIDENTE,-235.297.222.222,-466.319.444.444,SÃO PAULO,SP,...,20:15:00,SIM,FINALIZADA,A-042/CENIPA/2011,SIM,21/07/2011,11,1,NÃO,2010-12-14 20:15:00
6299,43450,43450,43450,43450,43450,ACIDENTE,-235.075,-466.344.444.444,SÃO PAULO,SP,...,10:55:00,SIM,FINALIZADA,A-085/CENIPA/2012,SIM,07/08/2012,6,1,NÃO,2010-11-04 10:55:00
6548,41411,41411,41411,41411,41411,INCIDENTE GRAVE,-235.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,19:30:00,SIM,FINALIZADA,IG-020/CENIPA/2011,SIM,30/06/2011,2,1,SIM,2010-06-08 19:30:00
6705,39992,39992,39992,39992,39992,ACIDENTE,-205.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,20:07:00,SIM,FINALIZADA,A-032/CENIPA/2012,SIM,22/03/2012,11,1,SIM,2010-02-17 20:07:00
6710,39275,39275,39275,39275,39275,ACIDENTE,-235.758.333.333,-467.022.222.222,SÃO PAULO,SP,...,09:03:00,SIM,FINALIZADA,A-009/CENIPA/2014,SIM,22/04/2016,3,1,NÃO,2010-02-10 09:03:00
6759,40069,40069,40069,40069,40069,ACIDENTE,-235.069.444.444,-466.341.666.667,SÃO PAULO,SP,...,14:50:00,SIM,FINALIZADA,A-121/CENIPA/2012,SIM,19/11/2012,8,1,NÃO,2010-01-10 14:50:00